import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    name: "Cricket Helmet",
    description: "Navy Blue",
    image: "Assets/helmet.jpeg",
    fastDelivery: false,
    inStock: true,
    bestSeller: true,
    price: "1100",
    discountedPrice: "1149",
    discount: "4",
    category: "Others",
    rating: "4.5",
    inStock: true,
    fastDelivery: true,
    qty: 0,
  },
  {
    _id: uuid(),
    name: "Kookaburra Bat",
    description: "Kashmir Willow ",
    image: "Assets/card-bat.jpg",
    fastDelivery: false,
    inStock: true,
    bestSeller: false,
    price: "1590",
    discountedPrice: "2850",
    discount: "44",
    category: "Bats",
    rating: "3.5",
    inStock: true,
    fastDelivery: false,
    qty: 0,
  },
  {
    _id: uuid(),
    name: "Batting Gloves",
    description: "Grey , White , Red ",
    image: "Assets/gloves.jpeg",
    fastDelivery: false,
    inStock: true,
    bestSeller: true,
    price: "849",
    discountedPrice: "919",
    discount: "7",
    category: "Others",
    rating: "4.2",
    inStock: true,
    fastDelivery: true,
    qty: 0,
  },
  {
    _id: uuid(),
    name: " Turf Pink Ball",
    description: "Pink Leather Ball",
    image: "Assets/pink-ball.jpeg",
    fastDelivery: false,
    inStock: true,
    bestSeller: false,
    price: "879",
    discountedPrice: "999",
    discount: "10",
    category: "Balls",
    rating: "3.1",
    inStock: true,
    fastDelivery: false,
    qty: 0,
  },
  {
    _id: uuid(),
    name: "Arm Guard",
    description: "White",
    image: "Assets/arm-guard.jpeg",
    fastDelivery: false,
    inStock: true,
    bestSeller: false,
    price: "289",
    discountedPrice: "299",
    discount: "3",
    category: "Others",
    rating: "2.6",
    inStock: false,
    fastDelivery: false,
    qty: 0,
  },
  {
    _id: uuid(),
    name: "Batting Pad",
    description: "White",
    image: "Assets/batting-pad.jpeg",
    fastDelivery: false,
    inStock: true,
    bestSeller: false,
    price: "1508",
    discountedPrice: "1999",
    discount: "24",
    category: "Others",
    rating: "1.2",
    inStock: true,
    fastDelivery: false,
    qty: 0,
  },
  {
    _id: uuid(),
    name: "SG Players Edition",
    description: "English Willow",
    image: "Assets/sg-bat-1.jpg",
    fastDelivery: false,
    inStock: true,
    bestSeller: true,
    price: "2459",
    discountedPrice: "2999",
    discount: "18",
    category: "Bats",
    rating: "3.0",
    inStock: true,
    fastDelivery: true,
    qty: 0,
  },
  {
    _id: uuid(),
    name: "SG Red Ball",
    description: "SG Standard Size",
    image: "Assets/sg-red-ball.jpg",
    fastDelivery: false,
    inStock: true,
    bestSeller: true,
    price: "1790",
    discountedPrice: "1999",
    discount: "8",
    category: "Balls",
    rating: "3.9",
    inStock: false,
    fastDelivery: true,
    qty: 0,
  },
  {
    _id: uuid(),
    name: "SS Josh",
    description: "Kashmir Willow",
    image: "Assets/ss-bat.webp",
    fastDelivery: false,
    inStock: true,
    bestSeller: true,
    price: "1699",
    discountedPrice: "1885",
    discount: "9",
    category: "Bats",
    rating: "4.0",
    inStock: true,
    fastDelivery: true,
    qty: 0,
  },
  {
    _id: uuid(),
    name: "Spartan Bat",
    description: "English Willow",
    image: "Assets/spartan-bat.webp",
    fastDelivery: false,
    inStock: true,
    bestSeller: true,
    price: "1943",
    discountedPrice: "2700",
    discount: "28",
    category: "Bats",
    rating: "3.5",
    inStock: false,
    fastDelivery: true,
    qty: 0,
  },
  {
    _id: uuid(),
    name: "Knocking Ball",
    description: "Red Training Ball",
    image: "Assets/hanging-ball.webp",
    fastDelivery: false,
    inStock: true,
    bestSeller: true,
    price: "129",
    discountedPrice: "499",
    discount: "74",
    category: "Balls",
    rating: "4.1",
    inStock: true,
    fastDelivery: true,
    qty: 0,
  },
  {
    _id: uuid(),
    name: "GM Mythos Bullet",
    description: "English Willow",
    image: "Assets/gm-bat.webp",
    fastDelivery: false,
    inStock: true,
    bestSeller: true,
    price: "2849",
    discountedPrice: "3329",
    discount: "14",
    category: "Bats",
    rating: "4.2",
    inStock: true,
    fastDelivery: true,
    qty: 0,
  },
  {
    _id: uuid(),
    name: "Kookaburra Verve",
    description: "Prodigy 60",
    image: "Assets/kookaburra-verve.webp",
    fastDelivery: false,
    inStock: true,
    bestSeller: true,
    price: "2849",
    discountedPrice: "3329",
    discount: "14",
    category: "Bats",
    rating: "4.2",
    inStock: true,
    fastDelivery: true,
    qty: 0,
  },
  {
    _id: uuid(),
    name: "CLUB Ball",
    description: "White Leather Ball",
    image: "Assets/white-ball.jpg",
    fastDelivery: false,
    inStock: true,
    bestSeller: true,
    price: "999",
    discountedPrice: "1499",
    discount: "11",
    category: "Balls",
    rating: "4.2",
    inStock: true,
    fastDelivery: true,
    qty: 0,
  },
];
